New feature to add genre.
qburst-sandeep-kumar/demo pull request #4
Opened 2022-02-28 08:59 UTC by jishnuqburst

New feature for add genre.

2022-03-03 01:55 UTC, qburst-sandeep-kumar requested changes

2022-03-03 01:55 UTC, qburst-sandeep-kumar commented on src/main/java/com/example/demo/service/impl/MastersServiceImpl.java
> +    }
it is better to return id of the newly inserted genre as response

2022-03-03 05:30 UTC, jishnuqburst reviewed
Applied meaningful names to functions and returned the last inserted id when inserting a new row.

2022-03-09 10:29 UTC, qburst-sandeep-kumar approved these changes

2022-03-10 08:54 UTC, merged